In [7]:
import numpy as np

# 일차원 배열 생성
a = np.array([0,1,2,3,4,5])
print(a)
print(np.shape(a))
print(np.size(a))

[0 1 2 3 4 5]
(6,)
6


In [8]:
# 2차원 배열 생성
b = np.array([[0,1,2], [3,4,5]])
print(b)
print(np.shape(b))
print(np.size(b))

[[0 1 2]
 [3 4 5]]
(2, 3)
6


In [9]:
# 3차원 배열 생성
c = np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
print(c)
print(np.shape(c))
print(np.size(c))

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
(2, 2, 3)
12


In [11]:
# 배열의 사이즈
d = [[1,2],[3,4],[5,6]]
print(len(d))
print(len(d[0]))
print(len(np.array(d)))

3
2
3


In [12]:
# 함수를 이용한 배열 생성
print(np.zeros(10))
print(np.ones(10))
print(np.random.rand(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.23444857 0.37154195 0.35107937 0.48648843 0.24693573 0.56747413
 0.57719144 0.86525184 0.6801103  0.00126164]


In [16]:
# 함수를 이용한 다차원 배열 생성
print(np.zeros((2, 3)))
print(np.ones((2, 2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [19]:
# arange 함수 이용
print(np.arange(0, 1, 0.1))
print(np.arange(10))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 1 2 3 4 5 6 7 8 9]


In [21]:
# linspace 함수 이용
print(np.linspace(0, 1, 11))
print(np.linspace(0, 1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [24]:
# reshape 메서드를 이용한 형태 변경
a = np.array([0,1,2,3,4,5,6,7])
b = a.reshape(2, 4)
print(b)

b = np.reshape(a, (2,4))
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [25]:
# reshape를 이용한 3차원 배열
c = b.reshape(2,2,2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [26]:
# 3차원 배열 => 2차원 배열
d = c.reshape(4,2)
print(d)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [27]:
# 1차원 배열로 변환
e = d.reshape(-1)
print(e)

[0 1 2 3 4 5 6 7]


In [28]:
# 원소 수를 자동으로 계산
f = e.reshape(2, -1)
print(f)

[[0 1 2 3]
 [4 5 6 7]]


In [30]:
# 배열과 수치의 연산
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print(a)
print(a + 3)
print(a * 3)

[[0 1 2]
 [3 4 5]]
[[3 4 5]
 [6 7 8]]
[[ 0  3  6]
 [ 9 12 15]]


In [31]:
# 배열과 배열의 연산
b = np.array([5,4,3,2,1,0]).reshape(2,3)
print(b)
print(a + b)
print(a * b)

[[5 4 3]
 [2 1 0]]
[[5 5 5]
 [5 5 5]]
[[0 4 6]
 [6 4 0]]
